In [ ]:
# Task 1
import numpy as np

array = np.arange(1, 11)
print(array)
print("Shape:", array.shape)
print("Size:", array.size)
print("Data type:", array.dtype)
print()

array = np.arange(1, 10).reshape(3, 3)
print(array)
print("Shape:", array.shape)
print("Size:", array.size)
print("Data type:", array.dtype)
print()

array = np.random.rand(3, 5, 3)
print(array)
print("Shape:", array.shape)
print("Size:", array.size)
print("Data type:", array.dtype)


[ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Size: 10
Data type: int32

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Size: 9
Data type: int32

[[[0.51891421 0.61108793 0.22466026]
  [0.56029203 0.96400448 0.2575127 ]
  [0.77774341 0.49429128 0.07560505]
  [0.57046684 0.00266308 0.64406544]
  [0.49847043 0.69171721 0.45092523]]

 [[0.65161213 0.02135081 0.69167758]
  [0.69066955 0.57194501 0.3492309 ]
  [0.49363009 0.25244266 0.72058043]
  [0.06015545 0.88281825 0.3560016 ]
  [0.48737826 0.69568288 0.68233367]]

 [[0.18893455 0.2306777  0.32948723]
  [0.41744047 0.78625312 0.56839898]
  [0.00899418 0.04778915 0.35781762]
  [0.07598651 0.03536504 0.76147351]
  [0.23997636 0.85848706 0.59813045]]]
Shape: (3, 5, 3)
Size: 45
Data type: float64


In [4]:
# Task 2
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]

print("Original data:", data)

print("First 3 elements:", data[:3])

print("All elements:", data[::2])

print ("Reverse Array:", data[::-1])


Original data: [10, 20, 30, 40, 50, 60, 70, 80, 90]
First 3 elements: [10, 20, 30]
All elements: [10, 30, 50, 70, 90]
Reverse Array: [90, 80, 70, 60, 50, 40, 30, 20, 10]


In [ ]:
# Task 3
array1 = np.random.randint(1,20,5)
array2 = np.random.randint(1,20,5)
print("Random array:", array1)
print("Random array:", array2)

sum = array1+array2
print("Sum of two arrays:", sum)

sub = array1-array2
print("Subtraction of two arrays:", sub)

mul = array1*array2
print("Multiplication of two arrays:", mul)

div = array1/array2
print("Division of two arrays:", div)

print()

dotproduct = np.dot(array1, array2)
print("Dot product of two arrays:", dotproduct)

mean = np.mean(array1)
median = np.median(array1)
std_dev = np.std(array1)
variance = np.var(array1)
print("Mean of array A:", mean)
print("Median of array A:", median)
print("Standard Deviation of array A:", std_dev)
print("Variance of array A:", variance)

max_value = np.max(array2)
min_value = np.min(array2)
max_index = np.argmax(array2)
min_index = np.argmin(array2)
print("Maximum value in array B:", max_value, "at index", max_index)
print("Minimum value in array B:", min_value, "at index", min_index)







Random array: [14  7 16  8  2]
Random array: [15 18  1 16  3]
Sum of two arrays: [29 25 17 24  5]
Subtraction of two arrays: [ -1 -11  15  -8  -1]
Multiplication of two arrays: [210 126  16 128   6]
Division of two arrays: [ 0.93333333  0.38888889 16.          0.5         0.66666667]

Dot product of two arrays: 486
Mean of array A: 9.4
Median of array A: 8.0
Standard Deviation of array A: 5.043808085167397
Variance of array A: 25.44
Maximum value in array B: 18 at index 1
Minimum value in array B: 1 at index 2


In [1]:
# Task 4
import numpy as np

array = np.arange(1, 13)
print("Original 1D Array:")
print(array)
print("Shape:", array.shape)
print()

array_2d = array.reshape(4, 3)
print("Reshaped to 2D (4x3):")
print(array_2d)
print("Shape:", array_2d.shape)
print()

array_3d = array.reshape(2, 2, 3)
print("Reshaped to 3D (2x2x3):")
print(array_3d)
print("Shape:", array_3d.shape)
print()

array_transposed = array_2d.T
print("Transposed 2D Array:")
print(array_transposed)
print("Shape:", array_transposed.shape)


Original 1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)

Reshaped to 2D (4x3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape: (4, 3)

Reshaped to 3D (2x2x3):
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)

Transposed 2D Array:
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Shape: (3, 4)


In [2]:
# Task 5

# 1. Create a NumPy array with 15 random integers between 10 and 50
array = np.random.randint(10, 51, size=15)
print("Original Array:")
print(array)
print()

# 2. Find all elements greater than 25
greater_than_25 = array[array > 25]
print("Elements greater than 25:")
print(greater_than_25)
print()

# 3. Replace all elements less than 30 with 0
array_with_zeros = array.copy()
array_with_zeros[array_with_zeros < 30] = 0
print("Array after replacing elements < 30 with 0:")
print(array_with_zeros)
print()

# 4. Count the number of elements divisible by 5
div_by_5_count = np.sum(array % 5 == 0)
print("Number of elements divisible by 5:", div_by_5_count)


Original Array:
[25 16 41 40 19 38 35 24 13 12 19 47 15 34 34]

Elements greater than 25:
[41 40 38 35 47 34 34]

Array after replacing elements < 30 with 0:
[ 0  0 41 40  0 38 35  0  0  0  0 47  0 34 34]

Number of elements divisible by 5: 4


In [4]:
# Task 6
import numpy as np

# 1. Create an array of 10 equally spaced values between 0 and 1
array_linspace = np.linspace(0, 1, 10)
print("Equally spaced values between 0 and 1:")
print(array_linspace)
print()

# 2. Create an identity matrix of size 4x4
identity_matrix = np.eye(4)
print("4x4 Identity Matrix:")
print(identity_matrix)
print()

# 3. Generate a 1D array of 20 random integers between 1 and 100
array_random = np.random.randint(1, 101, size=20)
print("Original Random Array:")
print(array_random)
print()

# Sort the array
sorted_array = np.sort(array_random)
print("Sorted Array:")
print(sorted_array)
print()

# Find the 5 largest elements
largest_five = sorted_array[-5:]
print("5 Largest Elements:")
print(largest_five)


Equally spaced values between 0 and 1:
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

4x4 Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Original Random Array:
[40 79 50 31 98 87 68  4 57 19 53 63 53  9 27 25 43 64 32 55]

Sorted Array:
[ 4  9 19 25 27 31 32 40 43 50 53 53 55 57 63 64 68 79 87 98]

5 Largest Elements:
[64 68 79 87 98]


In [5]:
import numpy as np
import time

A = np.random.rand(100, 100)
B = np.random.rand(100, 100)

start_time = time.time()

result = np.dot(A, B)

try:
    determinant = np.linalg.det(result)
    inverse = np.linalg.inv(result)
    invertible = True
except np.linalg.LinAlgError:
    determinant = None
    inverse = None
    invertible = False

end_time = time.time()
time_taken = end_time - start_time

print("Matrix multiplication completed.")
print("Determinant:", determinant)
print("Is Invertible:", invertible)
if invertible:
    print("Inverse matrix calculated.")
else:
    print("Inverse not possible (matrix is singular).")
print("Time taken: {:.4f} seconds".format(time_taken))


Matrix multiplication completed.
Determinant: 2.9749376257299714e+51
Is Invertible: True
Inverse matrix calculated.
Time taken: 0.0432 seconds
