In [ ]:
# Task 1
import numpy as np

array = np.arange(1, 11)
print(array)
print("Shape:", array.shape)
print("Size:", array.size)
print("Data type:", array.dtype)
print()

array = np.arange(1, 10).reshape(3, 3)
print(array)
print("Shape:", array.shape)
print("Size:", array.size)
print("Data type:", array.dtype)
print()

array = np.random.rand(3, 5, 3)
print(array)
print("Shape:", array.shape)
print("Size:", array.size)
print("Data type:", array.dtype)


[ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Size: 10
Data type: int32

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Size: 9
Data type: int32

[[[0.51891421 0.61108793 0.22466026]
  [0.56029203 0.96400448 0.2575127 ]
  [0.77774341 0.49429128 0.07560505]
  [0.57046684 0.00266308 0.64406544]
  [0.49847043 0.69171721 0.45092523]]

 [[0.65161213 0.02135081 0.69167758]
  [0.69066955 0.57194501 0.3492309 ]
  [0.49363009 0.25244266 0.72058043]
  [0.06015545 0.88281825 0.3560016 ]
  [0.48737826 0.69568288 0.68233367]]

 [[0.18893455 0.2306777  0.32948723]
  [0.41744047 0.78625312 0.56839898]
  [0.00899418 0.04778915 0.35781762]
  [0.07598651 0.03536504 0.76147351]
  [0.23997636 0.85848706 0.59813045]]]
Shape: (3, 5, 3)
Size: 45
Data type: float64


In [4]:
# Task 2
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]

print("Original data:", data)

print("First 3 elements:", data[:3])

print("All elements:", data[::2])

print ("Reverse Array:", data[::-1])


Original data: [10, 20, 30, 40, 50, 60, 70, 80, 90]
First 3 elements: [10, 20, 30]
All elements: [10, 30, 50, 70, 90]
Reverse Array: [90, 80, 70, 60, 50, 40, 30, 20, 10]


In [ ]:
# Task 3
array1 = np.random.randint(1,20,5)
array2 = np.random.randint(1,20,5)
print("Random array:", array1)
print("Random array:", array2)

sum = array1+array2
print("Sum of two arrays:", sum)

sub = array1-array2
print("Subtraction of two arrays:", sub)

mul = array1*array2
print("Multiplication of two arrays:", mul)

div = array1/array2
print("Division of two arrays:", div)

print()

dotproduct = np.dot(array1, array2)
print("Dot product of two arrays:", dotproduct)

mean = np.mean(array1)
median = np.median(array1)
std_dev = np.std(array1)
variance = np.var(array1)
print("Mean of array A:", mean)
print("Median of array A:", median)
print("Standard Deviation of array A:", std_dev)
print("Variance of array A:", variance)

max_value = np.max(array2)
min_value = np.min(array2)
max_index = np.argmax(array2)
min_index = np.argmin(array2)
print("Maximum value in array B:", max_value, "at index", max_index)
print("Minimum value in array B:", min_value, "at index", min_index)







Random array: [14  7 16  8  2]
Random array: [15 18  1 16  3]
Sum of two arrays: [29 25 17 24  5]
Subtraction of two arrays: [ -1 -11  15  -8  -1]
Multiplication of two arrays: [210 126  16 128   6]
Division of two arrays: [ 0.93333333  0.38888889 16.          0.5         0.66666667]

Dot product of two arrays: 486
Mean of array A: 9.4
Median of array A: 8.0
Standard Deviation of array A: 5.043808085167397
Variance of array A: 25.44
Maximum value in array B: 18 at index 1
Minimum value in array B: 1 at index 2
